-- AlterTable
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "aboutText" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "bulletPoints" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "attributes" JSONB;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "dimensions" TEXT;
ALTER TABLE "Product" ADD COLUMN IF NOT EXISTS "brand" TEXT;
